version: '3'

services:
  newsnow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsnow
    restart: always
    ports:
      - '4444:4444'
    volumes:
      - ./database:/usr/app/database
      - ./.env.server:/usr/app/.env.server
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - DATABASE_URL=file:/usr/app/database/newsnow.db
      - PRISMA_CLIENT_PATH=./server/utils/sequelizeClient.js
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
    command: sh -c "mkdir -p /usr/app/database && chmod 777 /usr/app/database && node --env-file .env.server --import ./esm-compat.js ./server/index.mjs"
