version: '3.8'

services:
  # API服务器
  newsnow-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SEARXNG_URL=http://searxng:8080
      - API_PORT=8088
      - API_HOST=0.0.0.0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - searxng
    networks:
      - newsnow-network

  # 定时任务服务（包含内容质量增强）
  newsnow-cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SEARXNG_URL=http://searxng:8080
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - searxng
    networks:
      - newsnow-network

  # SearxNG搜索服务
  searxng:
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080/
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped
    networks:
      - newsnow-network

networks:
  newsnow-network:
    driver: bridge

volumes:
  newsnow-data:
  newsnow-logs:
